'use client'

import React, { useEffect, useRef, useState } from 'react'
import mermaid from 'mermaid'

// Initialize Mermaid with custom dark theme colors fitting our glassmorphism UI
mermaid.initialize({
  startOnLoad: false,
  theme: 'dark',
  securityLevel: 'loose',
  themeVariables: {
    background: '#090d16',      // Slate 950 base
    primaryColor: '#1e40af',    // Blue 800
    primaryTextColor: '#f8fafc', // Slate 50
    lineColor: '#334155',        // Slate 700
    secondaryColor: '#581c87',  // Purple 800
    tertiaryColor: '#0f172a'     // Slate 900
  }
})

interface MermaidProps {
  chart: string
}

let chartIndex = 0

export default function Mermaid({ chart }: MermaidProps) {
  const [svg, setSvg] = useState<string>('')
  const [error, setError] = useState<string | null>(null)
  const isMounted = useRef(true)

  useEffect(() => {
    isMounted.current = true
    return () => {
      isMounted.current = false
    }
  }, [])

  useEffect(() => {
    chartIndex++
    const elementId = `mermaid-canvas-${chartIndex}`
    let errorTimeoutId: NodeJS.Timeout | null = null

    const compileDiagram = async () => {
      try {
        setError(null)
        let cleanChart = chart.trim()

        // 1. Strip ```mermaid ... ``` code fence if LLM included it
        cleanChart = cleanChart.replace(/^```mermaid\s*/i, '').replace(/```\s*$/i, '').trim()

        // 2. Normalize all smart/curly quotes to standard ASCII straight quotes
        cleanChart = cleanChart.replace(/[\u201C\u201D\u201E\u201F]/g, '"')

        // 2b. Sanitize parentheses INSIDE quoted node labels.
        //     Mermaid's parser treats ( and ) as special tokens even inside double-quoted strings.
        //     Replace them with dashes to prevent "got '1'" / parse errors.
        cleanChart = cleanChart.replace(/"([^"]*)"/g, (_match, inner) => {
          return '"' + inner.replace(/\(/g, '-').replace(/\)/g, '-') + '"'
        })

        // 3. Normalize the diagram: handle LLM single-line output
        //    The LLM sometimes outputs everything on 1-2 lines separated by spaces or semicolons.
        //    Strategy: if diagram has < 3 lines, rebuild it properly.
        const lineCount = cleanChart.split('\n').filter(l => l.trim()).length
        if (lineCount < 3) {
          // Step 3a: Split on semicolons (removes semicolons between statements)
          let tokens = cleanChart.split(/;\s*/)
          if (tokens.length < 3) {
            // Step 3b: No semicolons — LLM used spaces. Insert newlines before node patterns.
            // A "node statement" starts with an ID like A, B, C, etc. followed by [ or ( or { or -->
            // We insert a newline before each such pattern AFTER the first word (direction line)
            const firstLine = cleanChart.match(/^(graph\s+\w+|flowchart\s+\w+|sequenceDiagram|classDiagram|stateDiagram|gantt|pie|mindmap)/i)?.[0] || ''
            const rest = cleanChart.slice(firstLine.length)
            // Insert newline before node IDs: letter(s) followed by [ or ( or { or space+-->
            const reformatted = rest.replace(/\s{2,}(?=[A-Za-z_][\w]*(?:\[|\(|\{|(?:\s*-->)))/g, '\n    ')
            cleanChart = firstLine + reformatted
          } else {
            cleanChart = tokens.filter(t => t.trim().length > 0).join('\n    ')
          }
        }

        // 4. Simple fallback: prepend "graph TD" if no diagram type is declared
        if (
          !cleanChart.match(/^(graph|flowchart|sequenceDiagram|classDiagram|stateDiagram|gantt|pie|mindmap)/i)
        ) {
          cleanChart = `graph TD\n${cleanChart}`
        }

        const { svg: compiledSvg } = await mermaid.render(elementId, cleanChart)
        if (isMounted.current) {
          setError(null) // Clear any previous errors on success
          setSvg(compiledSvg)
        }
      } catch (err: any) {
        // Silently ignore parsing errors during active streaming.
        // We set a 1.5s timeout to display the error only if the stream stops/finishes and remains invalid.
        errorTimeoutId = setTimeout(() => {
          if (isMounted.current) {
            setError('Invalid flowchart syntax generated by AI.')
          }
        }, 1500)

        // Cleanup leftover canvas nodes generated by the failed compiler
        const badCanvas = document.getElementById(elementId)
        if (badCanvas) badCanvas.remove()
        const bindCanvas = document.getElementById(`d${elementId}`)
        if (bindCanvas) bindCanvas.remove()
      }
    }

    compileDiagram()

    return () => {
      if (errorTimeoutId) {
        clearTimeout(errorTimeoutId)
      }
    }
  }, [chart])

  if (error) {
    return (
      <div className="bg-zinc-950 border border-zinc-900 p-4 rounded-xl text-xs font-mono text-zinc-400 my-3">
        <div className="text-red-400 font-semibold mb-2">{error}</div>
        <pre className="overflow-x-auto whitespace-pre p-2 bg-zinc-900/50 rounded-lg">{chart}</pre>
      </div>
    )
  }

  return (
    <div 
      className="mermaid-wrapper w-full flex justify-center bg-zinc-900/30 border border-zinc-800/80 p-5 rounded-2xl my-3 overflow-x-auto shadow-inner backdrop-blur-sm"
      dangerouslySetInnerHTML={{ __html: svg || '<div class="text-xs text-zinc-500 animate-pulse">Rendering flowchart...</div>' }}
    />
  )
}
